import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { DEMO_TRADESPEOPLE } from "@/data/demo-tradespeople";

export const metadata: Metadata = { title: "Tradespeople on BuilderFind", description: "Browse BuilderFind trade profiles with verified experience, recent work and customer reviews." };

export default function Page() {
  return <>
    <Navbar />
    <main className="bg-[#E3F2FD] pb-16">
      <section className="border-b border-[#90CAF9] bg-white"><div className="mx-auto max-w-6xl px-4 py-14 sm:px-6 sm:py-20"><p className="text-xs font-black uppercase tracking-[0.18em] text-[#0D47A1]">Trade directory</p><h1 className="mt-4 max-w-3xl text-4xl font-black leading-tight tracking-tight text-[#0D47A1] sm:text-5xl">Profiles built around evidence, coverage and relevant work</h1><p className="mt-5 max-w-2xl text-base leading-7 text-black/70 sm:text-lg">See the people behind the work: their recent jobs, customer feedback, skills and service area. These featured profiles keep the directory useful while local tradespeople build their BuilderFind presence.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/post-a-job" className="rounded-full bg-[#0D47A1] px-6 py-3 text-sm font-bold text-white">Post a job free</Link><Link href="/builder-signup" className="rounded-full border border-[#2196F3] bg-white px-6 py-3 text-sm font-bold text-[#0D47A1]">Create a trade profile</Link></div></div></section>
      <section className="mx-auto max-w-6xl px-4 py-10 sm:px-6 sm:py-14"><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-[#2196F3]">Featured local specialists</p><h2 className="mt-2 text-2xl font-black text-[#0D47A1]">Meet five example profiles</h2></div><span className="rounded-full bg-white px-4 py-2 text-xs font-bold text-[#0D47A1]">{DEMO_TRADESPEOPLE.length} profiles · 5+ reviews each</span></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{DEMO_TRADESPEOPLE.map((profile) => <Link key={profile.slug} href={`/tradespeople/${profile.slug}`} className="group rounded-2xl border border-[#D7E8F6] bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:border-[#2196F3] hover:shadow-lg"><div className="flex items-center gap-3"><Image src={profile.avatar} width={52} height={52} alt={`${profile.owner} profile photo`} className="h-13 w-13 rounded-full object-cover ring-4 ring-[#E3F2FD]" /><div className="min-w-0"><h3 className="truncate text-sm font-black text-[#172B4D]">{profile.businessName}</h3><p className="mt-1 text-xs text-black/55">{profile.trade} · {profile.area}</p><p className="mt-1 text-xs"><span className="font-bold tracking-widest text-[#F6B800]">★★★★★</span> <span className="font-bold text-[#172B4D]">{profile.rating}</span> <span className="text-black/45">({profile.reviews.length})</span></p></div></div><p className="mt-4 line-clamp-3 text-xs leading-5 text-black/65">{profile.bio}</p><div className="mt-4 flex flex-wrap gap-1.5">{profile.services.slice(0, 3).map((service) => <span key={service} className="rounded-md bg-[#E3F2FD] px-2 py-1 text-[10px] font-bold text-[#0D47A1]">{service}</span>)}</div><div className="mt-5 flex items-center justify-between border-t border-[#D7E8F6] pt-4 text-xs font-bold text-[#0D47A1]"><span>{profile.completedJobs} completed jobs</span><span className="transition group-hover:translate-x-1">View profile →</span></div></Link>)}</div></section>
      <section className="border-y border-[#90CAF9] bg-white"><div className="mx-auto grid max-w-6xl gap-5 px-4 py-10 sm:grid-cols-3 sm:px-6"><div><p className="text-2xl font-black text-[#0D47A1]">5+</p><p className="mt-1 text-xs font-semibold text-black/60">Recent jobs shown per profile</p></div><div><p className="text-2xl font-black text-[#0D47A1]">Verified</p><p className="mt-1 text-xs font-semibold text-black/60">Identity and business checks highlighted</p></div><div><p className="text-2xl font-black text-[#0D47A1]">UK-wide</p><p className="mt-1 text-xs font-semibold text-black/60">Coverage and nearby trades visible</p></div></div></section>
    </main>
    <Footer />
  </>;
}
