import { ObjectId } from "mongodb";
import { apiUser } from "@/lib/auth/api-auth";
import { collections } from "@/lib/db/collections";
import { assertTrustedOrigin, jsonError, readJson, ApiError } from "@/lib/http/api";
import { id } from "@/lib/marketplace/access";
import { bookingUpdateSchema } from "@/lib/platform/schemas";
import { canTransitionBooking } from "@/lib/platform/state";
import { audit, publishEvent } from "@/lib/platform/events";

export async function PATCH(request: Request, context: RouteContext<"/api/bookings/[id]">) {
  try { assertTrustedOrigin(request); const user = await apiUser(); const bookingId = id((await context.params).id); const data = bookingUpdateSchema.parse(await readJson(request)); const c = await collections(); const booking = await c.bookings.findOne({ _id: bookingId }); if (!booking) throw new ApiError(404, "Booking not found", "NOT_FOUND"); if (user.role !== "admin" && ![booking.customerId.toHexString(), booking.builderId.toHexString()].includes(user.id)) throw new ApiError(403, "You are not part of this booking", "FORBIDDEN"); if (["confirmed", "in_progress"].includes(data.status) && user.role === "customer") throw new ApiError(403, "The builder must confirm and start the booking", "FORBIDDEN"); if (!canTransitionBooking(booking.status, data.status)) throw new ApiError(409, `A ${booking.status} booking cannot become ${data.status}`, "INVALID_STATE"); const now = new Date(); const extra = data.status === "completed" ? { completedAt: now } : {}; const result = await c.bookings.updateOne({ _id: bookingId, status: booking.status }, { $set: { ...data, ...extra, updatedAt: now } }); if (!result.modifiedCount) throw new ApiError(409, "This booking changed before your request completed", "STATE_CHANGED"); const jobStatus = data.status === "confirmed" ? "awarded" : data.status === "in_progress" ? "in_progress" : data.status === "completed" ? "completed" : data.status === "cancelled" ? "cancelled" : undefined; if (jobStatus) await c.jobs.updateOne({ _id: booking.jobId }, { $set: { status: jobStatus, updatedAt: now } }); if (data.status === "completed") await c.builderProfiles.updateOne({ userId: booking.builderId }, { $inc: { completedJobCount: 1 }, $set: { updatedAt: now } }); await Promise.all([audit({ actorId: new ObjectId(user.id), action: "booking.status_changed", entityType: "booking", entityId: bookingId, metadata: { from: booking.status, to: data.status } }), publishEvent({ type: "booking.updated", entityId: bookingId, audienceRoles: ["admin"], audienceUserIds: [booking.customerId, booking.builderId], payload: { status: data.status } })]); return Response.json({ ok: true }); } catch (error) { return jsonError(error); }
}
