// Generated by scripts/sync-cost-job-inventory.mjs on 2026-08-15.
// The inventory mirrors public job titles and taxonomy only; no third-party article prose is stored.

export type CostJobListing = {
  slug: string;
  title: string;
  categorySlugs: readonly string[];
};

export const COST_JOB_LISTINGS: readonly CostJobListing[] = [
  {
    "slug": "acoustic-plaster",
    "title": "Acoustic Plaster Cost",
    "categorySlugs": [
      "decorating-plastering"
    ]
  },
  {
    "slug": "acrylic-rendering",
    "title": "Acrylic Rendering Costs",
    "categorySlugs": [
      "external-finishes"
    ]
  },
  {
    "slug": "installing-air-conditioning",
    "title": "Air Conditioning Installation Cost",
    "categorySlugs": [
      "electrical-lighting"
    ]
  },
  {
    "slug": "air-source-heating-pump",
    "title": "Air Source Heat Pump Cost",
    "categorySlugs": [
      "plumbing-heating"
    ]
  },
  {
    "slug": "alarm-system",
    "title": "Alarm System Cost",
    "categorySlugs": [
      "electrical-lighting"
    ]
  },
  {
    "slug": "appliance-repair",
    "title": "Appliance Repair Cost Guide 2026",
    "categorySlugs": []
  },
  {
    "slug": "architect-prices",
    "title": "Architect Cost",
    "categorySlugs": [
      "conversions",
      "extensions"
    ]
  },
  {
    "slug": "replacing-skirting-and-architrave",
    "title": "Architrave and Skirting Board Fitting Cost",
    "categorySlugs": [
      "carpentry-windows-doors"
    ]
  },
  {
    "slug": "remove-artex",
    "title": "Artex Removal Cost",
    "categorySlugs": [
      "decorating-plastering"
    ]
  },
  {
    "slug": "artificial-grass-costs",
    "title": "Artificial Grass Installation Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "artificial-grass-installation-in-birmingham",
    "title": "Artificial Grass Installation Cost in Birmingham",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "artificial-grass-installation-in-bristol-cost",
    "title": "Artificial Grass Installation Cost in Bristol",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "artificial-grass-installation-in-edinburgh-cost",
    "title": "Artificial Grass Installation Cost in Edinburgh",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "artificial-grass-installation-in-glasgow-cost",
    "title": "Artificial Grass Installation Cost in Glasgow",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "artificial-grass-installation-in-leeds-cost",
    "title": "Artificial Grass Installation Cost in Leeds",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "artificial-grass-installation-in-liverpool-cost",
    "title": "Artificial Grass Installation Cost in Liverpool",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "artificial-grass-installation-in-london-cost",
    "title": "Artificial Grass Installation Cost in London",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "artificial-grass-installation-in-manchester-cost",
    "title": "Artificial Grass Installation Cost in Manchester",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "artificial-grass-installation-in-nottingham-cost",
    "title": "Artificial Grass Installation Cost in Nottingham",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "artificial-grass-installation-in-sheffield-cost",
    "title": "Artificial Grass Installation Cost in Sheffield",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "removing-asbestos-from-a-roof",
    "title": "Asbestos Removal Cost",
    "categorySlugs": [
      "roofs-chimneys"
    ]
  },
  {
    "slug": "installing-an-awning",
    "title": "Awning Installation Cost Guide (2026 Update)",
    "categorySlugs": []
  },
  {
    "slug": "basement-conversion",
    "title": "Basement Conversion Cost",
    "categorySlugs": [
      "conversions"
    ]
  },
  {
    "slug": "cost-of-installing-a-new-bath",
    "title": "Bath Installation Cost",
    "categorySlugs": [
      "bathrooms"
    ]
  },
  {
    "slug": "bathroom-extension",
    "title": "Bathroom Extension Cost",
    "categorySlugs": [
      "bathrooms"
    ]
  },
  {
    "slug": "bathroom-extractor-fan",
    "title": "Bathroom Extractor Fan Installation Cost",
    "categorySlugs": [
      "bathrooms",
      "electrical-lighting"
    ]
  },
  {
    "slug": "installing-bathroom-tv",
    "title": "Bathroom TV Installation Cost",
    "categorySlugs": [
      "bathrooms",
      "electrical-lighting"
    ]
  },
  {
    "slug": "changing-your-bay-window",
    "title": "Bay Window Replacement Cost",
    "categorySlugs": [
      "carpentry-windows-doors"
    ]
  },
  {
    "slug": "bay-window-roof-replacement",
    "title": "Bay Window Roof Replacement Cost",
    "categorySlugs": [
      "carpentry-windows-doors"
    ]
  },
  {
    "slug": "bee-nest-removal",
    "title": "Bee Nest Removal Cost Guide (UK Prices 2026)",
    "categorySlugs": []
  },
  {
    "slug": "bifold-doors",
    "title": "Bifold Door Installation Cost",
    "categorySlugs": [
      "carpentry-windows-doors"
    ]
  },
  {
    "slug": "biomass-boiler",
    "title": "Biomass Boiler Cost",
    "categorySlugs": [
      "plumbing-heating"
    ]
  },
  {
    "slug": "bleed-a-radiator",
    "title": "Bleeding Radiators Cost",
    "categorySlugs": [
      "plumbing-heating"
    ]
  },
  {
    "slug": "block-paving-cost",
    "title": "Block Paving Cost",
    "categorySlugs": [
      "driveways-paving"
    ]
  },
  {
    "slug": "installing-a-new-boiler",
    "title": "Boiler Installation Cost",
    "categorySlugs": [
      "plumbing-heating"
    ]
  },
  {
    "slug": "cost-to-get-your-boiler-serviced",
    "title": "Boiler Service Cost",
    "categorySlugs": [
      "plumbing-heating"
    ]
  },
  {
    "slug": "installing-a-hot-water-tap",
    "title": "Boiling Water Tap Installation Cost",
    "categorySlugs": [
      "plumbing-heating"
    ]
  },
  {
    "slug": "box-in-boiler",
    "title": "Box in Boiler Cost",
    "categorySlugs": [
      "plumbing-heating"
    ]
  },
  {
    "slug": "brick-driveway",
    "title": "Brick Driveway Cost",
    "categorySlugs": [
      "driveways-paving"
    ]
  },
  {
    "slug": "brick-shed",
    "title": "Brick Shed Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "bungalow-loft-conversion",
    "title": "Bungalow Loft Conversion Cost",
    "categorySlugs": [
      "conversions"
    ]
  },
  {
    "slug": "cost-of-capping-fascias-and-soffits",
    "title": "Capping Soffits and Fascias Cost",
    "categorySlugs": [
      "gutters-roofline",
      "roofs-chimneys"
    ]
  },
  {
    "slug": "caravan-decking",
    "title": "Caravan Decking Prices",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "carpet-cleaning",
    "title": "Carpet Cleaning Cost",
    "categorySlugs": [
      "flooring-carpets"
    ]
  },
  {
    "slug": "cost-of-laying-carpet",
    "title": "Carpet Fitting Cost",
    "categorySlugs": [
      "flooring-carpets"
    ]
  },
  {
    "slug": "cavity-wall-insulation",
    "title": "Cavity Wall Insulation Cost",
    "categorySlugs": [
      "energy-saving"
    ]
  },
  {
    "slug": "installing-cctv",
    "title": "CCTV Installation Cost",
    "categorySlugs": [
      "electrical-lighting"
    ]
  },
  {
    "slug": "ceiling-panelling",
    "title": "Ceiling Panelling Cost",
    "categorySlugs": [
      "carpentry-windows-doors"
    ]
  },
  {
    "slug": "replacing-a-ceiling",
    "title": "Ceiling Replacement Cost",
    "categorySlugs": [
      "decorating-plastering"
    ]
  },
  {
    "slug": "cement-rendering",
    "title": "Cement Render Cost",
    "categorySlugs": [
      "external-finishes"
    ]
  },
  {
    "slug": "installing-central-heating",
    "title": "Central Heating Installation Cost",
    "categorySlugs": [
      "plumbing-heating"
    ]
  },
  {
    "slug": "chain-link-fencing",
    "title": "Chain Link Fencing Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "bespoke-childs-bed-cost",
    "title": "Childs Bespoke Bed Cost",
    "categorySlugs": [
      "carpentry-windows-doors"
    ]
  },
  {
    "slug": "remove-chimney-breast",
    "title": "Chimney Breast Removal Cost",
    "categorySlugs": [
      "roofs-chimneys"
    ]
  },
  {
    "slug": "chimney-cowl-fitting",
    "title": "Chimney Cowl Fitting Cost",
    "categorySlugs": [
      "roofs-chimneys"
    ]
  },
  {
    "slug": "replacing-leadwork-on-a-chimney",
    "title": "Chimney Flashing Repair Cost",
    "categorySlugs": [
      "roofs-chimneys"
    ]
  },
  {
    "slug": "installing-a-chimney-liner",
    "title": "Chimney Liner Cost",
    "categorySlugs": [
      "roofs-chimneys"
    ]
  },
  {
    "slug": "chimney-repointing",
    "title": "Chimney Repointing Cost: How Much to Repoint a Chimney?",
    "categorySlugs": []
  },
  {
    "slug": "chimney-sweeping",
    "title": "Chimney Sweep Cost",
    "categorySlugs": [
      "roofs-chimneys"
    ]
  },
  {
    "slug": "cobblestone-driveway",
    "title": "Cobblestone Driveway Cost",
    "categorySlugs": [
      "driveways-paving"
    ]
  },
  {
    "slug": "cost-to-repair-a-drain-line-breakage",
    "title": "Collapsed Drain Repair Cost",
    "categorySlugs": [
      "drainage"
    ]
  },
  {
    "slug": "new-central-heating-cost",
    "title": "Combi Boiler Installation Cost",
    "categorySlugs": [
      "plumbing-heating"
    ]
  },
  {
    "slug": "cost-of-hiring-scaffolding",
    "title": "Complete Scaffolding Cost Guide (UK Prices 2026)",
    "categorySlugs": []
  },
  {
    "slug": "installing-composite-decking",
    "title": "Composite Decking Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "composite-fencing",
    "title": "Composite Fencing Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "concrete-a-driveway",
    "title": "Concrete Driveway Cost",
    "categorySlugs": [
      "driveways-paving"
    ]
  },
  {
    "slug": "concrete-driveway-repair",
    "title": "Concrete Driveway Repair Cost",
    "categorySlugs": [
      "driveways-paving"
    ]
  },
  {
    "slug": "concrete-edging-cost",
    "title": "Concrete Edging Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "concrete-gutter-replacement",
    "title": "Concrete Gutter Replacement Cost",
    "categorySlugs": [
      "gutters-roofline",
      "roofs-chimneys"
    ]
  },
  {
    "slug": "concrete-shed-base",
    "title": "Concrete Shed Base Cost: How Much to Lay a Concrete Base?",
    "categorySlugs": []
  },
  {
    "slug": "removing-conifer-tree",
    "title": "Conifer Tree Removal Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "conservatory-extension",
    "title": "Conservatory Cost",
    "categorySlugs": [
      "extensions"
    ]
  },
  {
    "slug": "conservatory-insulation",
    "title": "Conservatory Roof Insulation Cost Guide (2026 Update)",
    "categorySlugs": []
  },
  {
    "slug": "conservatory-roof-replacement-costs",
    "title": "Conservatory Roof Replacement Cost",
    "categorySlugs": [
      "carpentry-windows-doors",
      "roofs-chimneys"
    ]
  },
  {
    "slug": "replace-a-fuse-box",
    "title": "Consumer Unit Replacement Cost",
    "categorySlugs": [
      "electrical-lighting"
    ]
  },
  {
    "slug": "cooker-element-replacement",
    "title": "Cooker Element Replacement Cost UK",
    "categorySlugs": []
  },
  {
    "slug": "cooker-hood",
    "title": "Cooker Hood Installation Costs",
    "categorySlugs": []
  },
  {
    "slug": "corian-worktop",
    "title": "Corian Worktop Cost",
    "categorySlugs": [
      "kitchens"
    ]
  },
  {
    "slug": "building-a-dog-kennel",
    "title": "Cost of Building a Dog House",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "building-a-new-house",
    "title": "Cost of Building a House",
    "categorySlugs": [
      "conversions"
    ]
  },
  {
    "slug": "building-a-raised-garden-bed",
    "title": "Cost of Building a Raised Garden Bed",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "building-a-tree-house",
    "title": "Cost of Building a Tree House",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "hanging-curtains",
    "title": "Cost of Curtain Installation",
    "categorySlugs": [
      "carpentry-windows-doors"
    ]
  },
  {
    "slug": "upvc-windows-cost",
    "title": "Cost of Double Glazed Windows",
    "categorySlugs": [
      "carpentry-windows-doors"
    ]
  },
  {
    "slug": "installing-downstairs-toilet",
    "title": "Cost of Downstairs Toilet Installation",
    "categorySlugs": [
      "bathrooms"
    ]
  },
  {
    "slug": "installing-a-driveway-gate",
    "title": "Cost of Driveway Gates",
    "categorySlugs": [
      "driveways-paving"
    ]
  },
  {
    "slug": "installing-a-new-fitted-wardrobe",
    "title": "Cost of Fitted Wardrobes",
    "categorySlugs": [
      "carpentry-windows-doors"
    ]
  },
  {
    "slug": "fitting-pet-flaps",
    "title": "Cost of Fitting Pet Flaps",
    "categorySlugs": [
      "carpentry-windows-doors"
    ]
  },
  {
    "slug": "lawn-aeration",
    "title": "Cost of Lawn Aeration",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "lawn-scarification",
    "title": "Cost of Lawn Scarification",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "patio-design-installation-cost",
    "title": "Cost of Laying a Patio",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "laying-garden-turf",
    "title": "Cost of Laying Turf",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "metal-fencing",
    "title": "Cost of Metal Fencing",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "boiler-relocation",
    "title": "Cost of Moving a Boiler",
    "categorySlugs": [
      "plumbing-heating"
    ]
  },
  {
    "slug": "moving-a-kitchen-sink",
    "title": "Cost of Moving a Kitchen Sink",
    "categorySlugs": [
      "plumbing-heating"
    ]
  },
  {
    "slug": "moving-light-switch",
    "title": "Cost of Moving Light Switch",
    "categorySlugs": [
      "electrical-lighting"
    ]
  },
  {
    "slug": "planting-a-tree",
    "title": "Cost of Planting a Tree",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "drywalling-a-house",
    "title": "Cost of Plasterboard Installation",
    "categorySlugs": [
      "decorating-plastering",
      "external-finishes"
    ]
  },
  {
    "slug": "removing-pebbledash",
    "title": "Cost of Removing Pebbledash",
    "categorySlugs": [
      "external-finishes"
    ]
  },
  {
    "slug": "replacing-kitchen-cupboards",
    "title": "Cost of Replacing Kitchen Cupboard Doors (2026 Update)",
    "categorySlugs": []
  },
  {
    "slug": "repoint-brick-walls-on-a-house",
    "title": "Cost of Repointing a House",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "painting-soffits-and-fascias",
    "title": "Cost of Soffit and Fascia Painting",
    "categorySlugs": [
      "roofs-chimneys"
    ]
  },
  {
    "slug": "cost-of-installing-soundproofing",
    "title": "Cost of Soundproofing a Room",
    "categorySlugs": [
      "carpentry-windows-doors"
    ]
  },
  {
    "slug": "tyrolean-render",
    "title": "Cost of Tyrolean Render",
    "categorySlugs": [
      "decorating-plastering"
    ]
  },
  {
    "slug": "unblocking-a-toilet",
    "title": "Cost of Unblocking a Toilet",
    "categorySlugs": [
      "bathrooms",
      "plumbing-heating"
    ]
  },
  {
    "slug": "hang-bedroom-wallpaper",
    "title": "Cost of Wallpapering a Bedroom",
    "categorySlugs": [
      "decorating-plastering"
    ]
  },
  {
    "slug": "weeding",
    "title": "Cost of Weeding",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "build-a-fire-pit",
    "title": "Cost to Build a Fire Pit",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "garage-extension",
    "title": "Cost to Build a Garage",
    "categorySlugs": [
      "extensions"
    ]
  },
  {
    "slug": "build-a-garden-brick-wall",
    "title": "Cost to Build a Garden Wall",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "build-a-greenhouse",
    "title": "Cost to Build a Greenhouse",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "pond-prices",
    "title": "Cost to Build a Pond",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "build-a-porch",
    "title": "Cost to Build a Porch",
    "categorySlugs": [
      "extensions"
    ]
  },
  {
    "slug": "build-gazebo",
    "title": "Cost to Build Gazebo",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "build-outdoor-kitchen",
    "title": "Cost to Build Outdoor Kitchen",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "cost-of-converting-a-garage-into-a-bedroom",
    "title": "Cost to Convert Garage to Bedroom",
    "categorySlugs": [
      "conversions",
      "extensions"
    ]
  },
  {
    "slug": "extend-over-garage",
    "title": "Cost to Extend Over Garage",
    "categorySlugs": [
      "extensions"
    ]
  },
  {
    "slug": "velux-window-skylight",
    "title": "Cost To Install Velux Windows",
    "categorySlugs": [
      "carpentry-windows-doors"
    ]
  },
  {
    "slug": "moving-a-radiator",
    "title": "Cost to Move a Radiator",
    "categorySlugs": [
      "plumbing-heating"
    ]
  },
  {
    "slug": "gas-and-electric-meters",
    "title": "Cost to Move Electric Meter and Gas Meter",
    "categorySlugs": [
      "electrical-lighting",
      "plumbing-heating"
    ]
  },
  {
    "slug": "painting-a-bedroom",
    "title": "Cost to Paint a Room",
    "categorySlugs": [
      "decorating-plastering"
    ]
  },
  {
    "slug": "painting-house-exterior",
    "title": "Cost to Paint Exterior of House",
    "categorySlugs": [
      "decorating-plastering",
      "external-finishes"
    ]
  },
  {
    "slug": "pebble-dash-a-home",
    "title": "Cost to Pebble Dash a House",
    "categorySlugs": [
      "external-finishes"
    ]
  },
  {
    "slug": "plaster-a-ceiling",
    "title": "Cost to Plaster a Ceiling",
    "categorySlugs": [
      "decorating-plastering"
    ]
  },
  {
    "slug": "re-grouting-bathroom",
    "title": "Cost to Regrout Bathroom Tiles",
    "categorySlugs": [
      "bathrooms"
    ]
  },
  {
    "slug": "remove-concrete-driveway",
    "title": "Cost to Remove Concrete Driveway",
    "categorySlugs": [
      "driveways-paving"
    ]
  },
  {
    "slug": "remove-plaster",
    "title": "Cost to Remove Plaster",
    "categorySlugs": [
      "decorating-plastering"
    ]
  },
  {
    "slug": "remove-render",
    "title": "Cost to Remove Render",
    "categorySlugs": [
      "decorating-plastering"
    ]
  },
  {
    "slug": "floorboard-repair",
    "title": "Cost to Replace Floorboards",
    "categorySlugs": [
      "carpentry-windows-doors",
      "flooring-carpets"
    ]
  },
  {
    "slug": "replacing-roof-tiles",
    "title": "Cost to Replace Roof Tiles",
    "categorySlugs": [
      "roofs-chimneys"
    ]
  },
  {
    "slug": "resealing-windows-and-doors",
    "title": "Cost to Reseal Windows and Doors",
    "categorySlugs": [
      "carpentry-windows-doors"
    ]
  },
  {
    "slug": "shower-retiling",
    "title": "Cost to Retile a Shower",
    "categorySlugs": [
      "bathrooms"
    ]
  },
  {
    "slug": "cost-to-skim-a-room",
    "title": "Cost to Skim a Room",
    "categorySlugs": [
      "decorating-plastering"
    ]
  },
  {
    "slug": "tiling-a-bathroom",
    "title": "Cost to Tile a Bathroom",
    "categorySlugs": [
      "bathrooms"
    ]
  },
  {
    "slug": "fitting-coving",
    "title": "Coving Installation Cost",
    "categorySlugs": [
      "decorating-plastering"
    ]
  },
  {
    "slug": "damp-proofing-a-wall",
    "title": "Damp Proof Course Cost",
    "categorySlugs": [
      "conversions"
    ]
  },
  {
    "slug": "demolition",
    "title": "Demolition Cost",
    "categorySlugs": [
      "conversions"
    ]
  },
  {
    "slug": "installing-a-disabled",
    "title": "Disabled Lift in House Cost",
    "categorySlugs": [
      "electrical-lighting"
    ]
  },
  {
    "slug": "dishwasher-installation",
    "title": "Dishwasher Installation Cost",
    "categorySlugs": [
      "electrical-lighting"
    ]
  },
  {
    "slug": "dishwasher-repair",
    "title": "Dishwasher Repair Cost in the UK",
    "categorySlugs": []
  },
  {
    "slug": "door-frame-replacement",
    "title": "Door Frame Replacement Cost",
    "categorySlugs": [
      "carpentry-windows-doors"
    ]
  },
  {
    "slug": "dormer-loft-conversion",
    "title": "Dormer Loft Conversion Cost",
    "categorySlugs": [
      "conversions",
      "extensions"
    ]
  },
  {
    "slug": "condensation-removal",
    "title": "Double Glazing Condensation Repair Cost",
    "categorySlugs": [
      "carpentry-windows-doors"
    ]
  },
  {
    "slug": "double-storey-extension",
    "title": "Double Storey Extension Cost",
    "categorySlugs": [
      "extensions"
    ]
  },
  {
    "slug": "drain-survey-cost",
    "title": "Drain Survey Cost",
    "categorySlugs": [
      "plumbing-heating",
      "drainage"
    ]
  },
  {
    "slug": "clean-and-unclog-drains",
    "title": "Drain Unblocking Cost",
    "categorySlugs": [
      "drainage"
    ]
  },
  {
    "slug": "drip-irrigation-system",
    "title": "Drip Irrigation System Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "power-wash-a-driveway",
    "title": "Driveway Cleaning Cost",
    "categorySlugs": [
      "driveways-paving",
      "gardens-fences"
    ]
  },
  {
    "slug": "driveway-resurfacing",
    "title": "Driveway Resurfacing Cost: How Much to Resurface a Driveway?",
    "categorySlugs": []
  },
  {
    "slug": "driveway-sealing",
    "title": "Driveway Sealing Cost",
    "categorySlugs": [
      "driveways-paving"
    ]
  },
  {
    "slug": "dropping-a-kerb",
    "title": "Dropped Kerb Cost",
    "categorySlugs": [
      "driveways-paving"
    ]
  },
  {
    "slug": "dry-ridge-system-installation",
    "title": "Dry Ridge System Installation Cost Guide (UK)",
    "categorySlugs": []
  },
  {
    "slug": "dry-verge-system-installation",
    "title": "Dry Verge System Installation Cost",
    "categorySlugs": [
      "roofs-chimneys"
    ]
  },
  {
    "slug": "installing-a-durgo-valve",
    "title": "Durgo Valve Installation Cost",
    "categorySlugs": [
      "plumbing-heating"
    ]
  },
  {
    "slug": "electrical-safety-certificate",
    "title": "EICR Certificate Cost",
    "categorySlugs": [
      "electrical-lighting"
    ]
  },
  {
    "slug": "electric-cooker-installation",
    "title": "Electric Cooker Installation Cost",
    "categorySlugs": [
      "electrical-lighting"
    ]
  },
  {
    "slug": "installing-electric-garden-gates",
    "title": "Electric Gates Cost",
    "categorySlugs": [
      "electrical-lighting",
      "driveways-paving"
    ]
  },
  {
    "slug": "electric-oven-repair",
    "title": "Electric Oven Repair Cost UK",
    "categorySlugs": []
  },
  {
    "slug": "electric-radiator",
    "title": "Electric Radiator Cost UK 2026",
    "categorySlugs": []
  },
  {
    "slug": "emergency-plumbing",
    "title": "Emergency Plumber Cost",
    "categorySlugs": [
      "bathrooms",
      "plumbing-heating"
    ]
  },
  {
    "slug": "end-of-tenancy-cleaning-costs",
    "title": "End of Tenancy Clean Cost Guide (UK Prices 2026)",
    "categorySlugs": []
  },
  {
    "slug": "install-ev-charging-station",
    "title": "EV Charger Installation Cost",
    "categorySlugs": [
      "electrical-lighting",
      "energy-saving"
    ]
  },
  {
    "slug": "painting-exterior-doors",
    "title": "Exterior Door Painting Cost",
    "categorySlugs": [
      "carpentry-windows-doors",
      "decorating-plastering",
      "external-finishes"
    ]
  },
  {
    "slug": "fake-chimney-breast",
    "title": "Fake Chimney Breast Cost: Building a Fake Chimney Breast",
    "categorySlugs": []
  },
  {
    "slug": "felt-roof-replacement",
    "title": "Felt Roof Replacement Cost",
    "categorySlugs": [
      "roofs-chimneys"
    ]
  },
  {
    "slug": "replacing-garden-fences",
    "title": "Fence Installation Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "fence-removal",
    "title": "Fence Removal Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "fence-repair",
    "title": "Fence Repair Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "fire-door",
    "title": "Fire Door Installation Cost",
    "categorySlugs": [
      "carpentry-windows-doors"
    ]
  },
  {
    "slug": "fire-installation",
    "title": "Fireplace Installation Cost",
    "categorySlugs": [
      "plumbing-heating"
    ]
  },
  {
    "slug": "fitting-spotlights-and-downlights",
    "title": "Fitting Spotlights and Downlights Cost",
    "categorySlugs": [
      "electrical-lighting"
    ]
  },
  {
    "slug": "flat-pack-furniture",
    "title": "Flat Pack Furniture Assembly Cost",
    "categorySlugs": [
      "carpentry-windows-doors"
    ]
  },
  {
    "slug": "flat-pack-home-cost",
    "title": "Flat Pack Homes Cost",
    "categorySlugs": [
      "conversions",
      "extensions"
    ]
  },
  {
    "slug": "flat-pack-extensions-cost",
    "title": "Flat Pack House Extension Cost",
    "categorySlugs": [
      "conversions",
      "extensions"
    ]
  },
  {
    "slug": "flat-panel-radiator",
    "title": "Flat Panel Radiator Cost",
    "categorySlugs": [
      "plumbing-heating"
    ]
  },
  {
    "slug": "flat-roof-extension",
    "title": "Flat Roof Extension Cost",
    "categorySlugs": [
      "extensions"
    ]
  },
  {
    "slug": "flat-roof-construction-cost",
    "title": "Flat Roof Replacement Cost",
    "categorySlugs": [
      "roofs-chimneys"
    ]
  },
  {
    "slug": "flat-roof-replacement-birmingham-cost",
    "title": "Flat Roof Replacement Cost in Birmingham (2026 Prices)",
    "categorySlugs": []
  },
  {
    "slug": "flat-roof-replacement-bristol-cost",
    "title": "Flat Roof Replacement Cost in Bristol",
    "categorySlugs": [
      "roofs-chimneys"
    ]
  },
  {
    "slug": "flat-roof-replacement-edinburgh-cost",
    "title": "Flat Roof Replacement Cost in Edinburgh",
    "categorySlugs": [
      "roofs-chimneys"
    ]
  },
  {
    "slug": "flat-roof-replacement-glasgow-cost",
    "title": "Flat Roof Replacement Cost in Glasgow",
    "categorySlugs": [
      "roofs-chimneys"
    ]
  },
  {
    "slug": "flat-roof-replacement-cost-in-leeds",
    "title": "Flat Roof Replacement Cost in Leeds",
    "categorySlugs": [
      "roofs-chimneys"
    ]
  },
  {
    "slug": "flat-roof-replacement-cost-in-liverpool",
    "title": "Flat Roof Replacement Cost in Liverpool",
    "categorySlugs": [
      "roofs-chimneys"
    ]
  },
  {
    "slug": "flat-roof-replacement-london-cost",
    "title": "Flat Roof Replacement Cost in London",
    "categorySlugs": [
      "roofs-chimneys"
    ]
  },
  {
    "slug": "flat-roof-replacement-cost-in-manchester",
    "title": "Flat Roof Replacement Cost in Manchester",
    "categorySlugs": [
      "roofs-chimneys"
    ]
  },
  {
    "slug": "flat-roof-replacement-nottingham-cost",
    "title": "Flat Roof Replacement Cost in Nottingham",
    "categorySlugs": [
      "roofs-chimneys"
    ]
  },
  {
    "slug": "flat-roof-replacement-sheffield-cost",
    "title": "Flat Roof Replacement Cost in Sheffield",
    "categorySlugs": [
      "roofs-chimneys"
    ]
  },
  {
    "slug": "installing-floor-insulation",
    "title": "Floor Insulation Cost",
    "categorySlugs": [
      "flooring-carpets"
    ]
  },
  {
    "slug": "floor-screeding-cost",
    "title": "Floor Screeding Cost",
    "categorySlugs": [
      "flooring-carpets"
    ]
  },
  {
    "slug": "tiling-a-floor",
    "title": "Floor Tiling Cost",
    "categorySlugs": [
      "flooring-carpets"
    ]
  },
  {
    "slug": "installing-french-doors",
    "title": "French Door Installation Cost",
    "categorySlugs": [
      "carpentry-windows-doors"
    ]
  },
  {
    "slug": "fridge-freezer-repair",
    "title": "Fridge Freezer Repair Costs in the UK",
    "categorySlugs": []
  },
  {
    "slug": "garage-conversion-cost",
    "title": "Garage Conversion Cost",
    "categorySlugs": [
      "conversions",
      "extensions"
    ]
  },
  {
    "slug": "garage-demolition",
    "title": "Garage Demolition Costs: How Much to Demolish a Garage?",
    "categorySlugs": []
  },
  {
    "slug": "replacing-garage-roof",
    "title": "Garage Roof Replacement Cost",
    "categorySlugs": [
      "roofs-chimneys"
    ]
  },
  {
    "slug": "garden-decking",
    "title": "Garden Decking Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "garden-design",
    "title": "Garden Design Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "hanging-a-gate",
    "title": "Garden Gate Installation Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "landscaping-costs",
    "title": "Garden Landscaping Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "garden-levelling",
    "title": "Garden Levelling Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "hiring-a-gardener",
    "title": "Garden Maintenance Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "garden-office",
    "title": "Garden Office Cost",
    "categorySlugs": [
      "extensions"
    ]
  },
  {
    "slug": "garden-renovation",
    "title": "Garden Renovation Costs",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "garden-room",
    "title": "Garden Room Cost",
    "categorySlugs": [
      "extensions"
    ]
  },
  {
    "slug": "fitting-brick-stone-steps-cost",
    "title": "Garden Steps Cost",
    "categorySlugs": [
      "conversions",
      "gardens-fences"
    ]
  },
  {
    "slug": "garden-waste-removal",
    "title": "Garden Waste Removal Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "garden-water-feature-installation-cost",
    "title": "Garden Water Feature Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "installing-a-gas-cooker",
    "title": "Gas Cooker Cost 2026: How Much to Install a Gas Cooker?",
    "categorySlugs": []
  },
  {
    "slug": "installing-gas-fire-cost",
    "title": "Gas Fire Cost",
    "categorySlugs": [
      "plumbing-heating"
    ]
  },
  {
    "slug": "gas-fire-removal",
    "title": "Gas Fire Removal Cost",
    "categorySlugs": [
      "plumbing-heating"
    ]
  },
  {
    "slug": "servicing-a-gas-fire",
    "title": "Gas Fire Service Cost",
    "categorySlugs": [
      "plumbing-heating"
    ]
  },
  {
    "slug": "cost-of-running-gas-to-a-property",
    "title": "Gas Installation Cost",
    "categorySlugs": [
      "plumbing-heating",
      "energy-saving"
    ]
  },
  {
    "slug": "glass-room-extension",
    "title": "Glass Room Extension Cost",
    "categorySlugs": [
      "extensions"
    ]
  },
  {
    "slug": "glass-staircase",
    "title": "Glass Staircase Cost in 2026: How Much is a Glass Staircase?",
    "categorySlugs": []
  },
  {
    "slug": "granny-annexe",
    "title": "Granny Annexe Cost",
    "categorySlugs": [
      "extensions"
    ]
  },
  {
    "slug": "grass-cutting",
    "title": "Grass Cutting Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "gravel-driveway-costs",
    "title": "Gravel Driveway Cost",
    "categorySlugs": [
      "driveways-paving"
    ]
  },
  {
    "slug": "green-roof",
    "title": "Green Roof Cost: Installation Prices & Guide",
    "categorySlugs": []
  },
  {
    "slug": "installing-ground-source-heat-pump",
    "title": "Ground Source Heat Pump Cost",
    "categorySlugs": [
      "plumbing-heating"
    ]
  },
  {
    "slug": "cleaning-your-guttering",
    "title": "Gutter Cleaning Cost",
    "categorySlugs": [
      "drainage",
      "gutters-roofline"
    ]
  },
  {
    "slug": "repairing-guttering",
    "title": "Gutter Repair Cost",
    "categorySlugs": [
      "gutters-roofline"
    ]
  },
  {
    "slug": "replace-guttering",
    "title": "Gutter Replacement Cost",
    "categorySlugs": [
      "drainage",
      "gutters-roofline",
      "roofs-chimneys"
    ]
  },
  {
    "slug": "gypsum-plaster",
    "title": "Gypsum Plaster Cost Guide: UK Prices for 2026",
    "categorySlugs": [
      "decorating-plastering"
    ]
  },
  {
    "slug": "heated-driveway",
    "title": "Heated Driveway Cost",
    "categorySlugs": [
      "driveways-paving"
    ]
  },
  {
    "slug": "heated-towel-rail",
    "title": "Heated Towel Rail Installation Cost",
    "categorySlugs": [
      "bathrooms",
      "plumbing-heating"
    ]
  },
  {
    "slug": "removing-hedges",
    "title": "Hedge Removal Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "hip-to-gable-loft-conversion-cost",
    "title": "Hip to Gable Loft Conversion Cost",
    "categorySlugs": [
      "conversions"
    ]
  },
  {
    "slug": "holly-tree-removal",
    "title": "Holly Tree Removal Cost Guide 2026",
    "categorySlugs": []
  },
  {
    "slug": "installing-home-security",
    "title": "Home Security System Cost",
    "categorySlugs": [
      "electrical-lighting"
    ]
  },
  {
    "slug": "external-cladding-or-rendering-costs",
    "title": "House Cladding Cost",
    "categorySlugs": [
      "external-finishes"
    ]
  },
  {
    "slug": "house-clearance",
    "title": "House Clearance Cost Guide (UK Prices 2026)",
    "categorySlugs": []
  },
  {
    "slug": "house-extension",
    "title": "House Extension Cost",
    "categorySlugs": [
      "extensions"
    ]
  },
  {
    "slug": "removals-cost",
    "title": "House Removal Cost Guide (UK Prices 2026)",
    "categorySlugs": []
  },
  {
    "slug": "rendering-a-house",
    "title": "House Rendering Cost",
    "categorySlugs": [
      "external-finishes"
    ]
  },
  {
    "slug": "rewiring-a-house",
    "title": "House Rewire Cost",
    "categorySlugs": [
      "electrical-lighting"
    ]
  },
  {
    "slug": "house-rewire-cost-in-birmingham",
    "title": "House Rewire Cost Birmingham (2026 Prices)",
    "categorySlugs": []
  },
  {
    "slug": "house-rewire-cost-in-bristol",
    "title": "House Rewire Cost in Bristol (2026 Prices)",
    "categorySlugs": []
  },
  {
    "slug": "house-rewire-cost-in-edinburgh",
    "title": "House Rewire Cost in Edinburgh (2026 Prices)",
    "categorySlugs": []
  },
  {
    "slug": "house-rewire-cost-in-glasgow",
    "title": "House Rewire Cost in Glasgow (2026 Prices)",
    "categorySlugs": []
  },
  {
    "slug": "house-rewire-cost-in-leeds",
    "title": "House Rewire Cost in Leeds (2026 Prices)",
    "categorySlugs": []
  },
  {
    "slug": "house-rewire-cost-in-liverpool",
    "title": "House Rewire Cost in Liverpool (2026 Prices)",
    "categorySlugs": []
  },
  {
    "slug": "house-rewire-cost-in-london",
    "title": "House Rewire Cost in London (2026 Prices)",
    "categorySlugs": []
  },
  {
    "slug": "house-rewire-cost-in-manchester",
    "title": "House Rewire Cost in Manchester (2026 Prices)",
    "categorySlugs": []
  },
  {
    "slug": "house-rewire-cost-in-nottingham",
    "title": "House Rewire Cost in Nottingham (2026 Prices)",
    "categorySlugs": []
  },
  {
    "slug": "house-rewire-cost-in-sheffield",
    "title": "House Rewire Cost in Sheffield (2026 Prices)",
    "categorySlugs": []
  },
  {
    "slug": "granite-worktops",
    "title": "How Much Are Granite Worktops? (2026 Granite Worktop Prices)",
    "categorySlugs": []
  },
  {
    "slug": "false-suspended-ceiling",
    "title": "How Much Do Suspended Ceilings Cost? False Ceilings Price Guide",
    "categorySlugs": []
  },
  {
    "slug": "fibreglass-roofing",
    "title": "How Much Does a Fibreglass Roof Cost? (2026 UK Prices)",
    "categorySlugs": []
  },
  {
    "slug": "surveying-a-house",
    "title": "How Much Does a House Survey Cost? (UK Prices 2026)",
    "categorySlugs": []
  },
  {
    "slug": "loft-conversion-in-london-cost",
    "title": "How Much Does a Loft Conversion Cost in London in 2026?",
    "categorySlugs": []
  },
  {
    "slug": "tiled-conservatory-roof",
    "title": "How Much Does a Tiled Conservatory Roof Cost UK 2026?",
    "categorySlugs": []
  },
  {
    "slug": "how-much-does-it-cost-to-apply-lining-paper",
    "title": "How Much Does It Cost to Apply Lining Paper?",
    "categorySlugs": [
      "decorating-plastering",
      "external-finishes"
    ]
  },
  {
    "slug": "house-demolition",
    "title": "How Much Does It Cost to Demolish a House? (UK Prices 2026)",
    "categorySlugs": []
  },
  {
    "slug": "how-much-does-it-cost-to-paint-a-bathroom",
    "title": "How Much Does it Cost to Paint a Bathroom?",
    "categorySlugs": [
      "decorating-plastering",
      "external-finishes"
    ]
  },
  {
    "slug": "how-much-does-it-cost-to-paint-a-hallway",
    "title": "How Much Does It Cost to Paint a Hallway?",
    "categorySlugs": [
      "decorating-plastering",
      "external-finishes"
    ]
  },
  {
    "slug": "how-much-does-it-cost-to-paint-a-kitchen",
    "title": "How Much Does it Cost to Paint a Kitchen?",
    "categorySlugs": [
      "decorating-plastering",
      "external-finishes"
    ]
  },
  {
    "slug": "how-much-does-it-cost-to-paint-a-living-room",
    "title": "How Much Does it Cost to Paint a Living Room?",
    "categorySlugs": [
      "decorating-plastering",
      "external-finishes"
    ]
  },
  {
    "slug": "how-much-does-it-cost-to-paint-radiators",
    "title": "How Much Does It Cost to Paint Radiators?",
    "categorySlugs": [
      "decorating-plastering",
      "external-finishes"
    ]
  },
  {
    "slug": "how-much-does-it-cost-to-paint-tiles",
    "title": "How Much Does It Cost to Paint Tiles?",
    "categorySlugs": [
      "decorating-plastering",
      "external-finishes"
    ]
  },
  {
    "slug": "wall-tile-installation",
    "title": "How Much Does It Cost to Tile a Wall? Wall Tiling Price Guide 2026",
    "categorySlugs": []
  },
  {
    "slug": "replacing-an-immersion-heater-cost",
    "title": "Immersion Heater Cost",
    "categorySlugs": [
      "bathrooms",
      "plumbing-heating"
    ]
  },
  {
    "slug": "imprinted-concrete",
    "title": "Imprinted Concrete Driveway Cost",
    "categorySlugs": [
      "driveways-paving"
    ]
  },
  {
    "slug": "installing-infrared-heating",
    "title": "Infrared Heating Cost",
    "categorySlugs": [
      "electrical-lighting",
      "plumbing-heating"
    ]
  },
  {
    "slug": "installing-a-cast-iron-radiator",
    "title": "Installing a Cast Iron Radiator Cost",
    "categorySlugs": [
      "plumbing-heating"
    ]
  },
  {
    "slug": "install-a-column-radiator",
    "title": "Installing a Column Radiator Cost",
    "categorySlugs": []
  },
  {
    "slug": "installing-a-hydrogen-boiler",
    "title": "Installing a Hydrogen Boiler Cost",
    "categorySlugs": [
      "plumbing-heating"
    ]
  },
  {
    "slug": "installing-blinds",
    "title": "Installing Blinds Cost Guide 2026",
    "categorySlugs": [
      "carpentry-windows-doors"
    ]
  },
  {
    "slug": "installing-carport",
    "title": "Installing Carport Cost Guide: How Much is a Carport?",
    "categorySlugs": []
  },
  {
    "slug": "installing-heat-recovery-system",
    "title": "Installing Heat Recovery System Cost",
    "categorySlugs": [
      "plumbing-heating"
    ]
  },
  {
    "slug": "irrigation-system-installation",
    "title": "Irrigation System Installation Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "japanese-knotweed-removal",
    "title": "Japanese Knotweed Removal Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "karndean-flooring-cost",
    "title": "Karndean Flooring Cost",
    "categorySlugs": [
      "flooring-carpets"
    ]
  },
  {
    "slug": "kitchen-units",
    "title": "Kitchen Cabinet Installation Cost",
    "categorySlugs": [
      "carpentry-windows-doors",
      "kitchens"
    ]
  },
  {
    "slug": "kitchen-extension",
    "title": "Kitchen Extension Cost",
    "categorySlugs": [
      "kitchens",
      "extensions"
    ]
  },
  {
    "slug": "remodel-a-kitchen",
    "title": "Kitchen Fitting Cost",
    "categorySlugs": [
      "carpentry-windows-doors",
      "kitchens"
    ]
  },
  {
    "slug": "kitchen-flooring",
    "title": "Kitchen Flooring Cost",
    "categorySlugs": [
      "flooring-carpets"
    ]
  },
  {
    "slug": "replace-kitchen-sink",
    "title": "Kitchen Sink Replacement Cost",
    "categorySlugs": [
      "plumbing-heating"
    ]
  },
  {
    "slug": "replace-kitchen-worktops",
    "title": "Kitchen Worktop Replacement Cost",
    "categorySlugs": [
      "carpentry-windows-doors",
      "kitchens"
    ]
  },
  {
    "slug": "kitchen-wrapping",
    "title": "Kitchen Wrapping Cost",
    "categorySlugs": [
      "decorating-plastering"
    ]
  },
  {
    "slug": "laying-laminate-floor",
    "title": "Laminate Flooring Cost",
    "categorySlugs": [
      "flooring-carpets"
    ]
  },
  {
    "slug": "laminate-worktop",
    "title": "Laminate Worktop Cost",
    "categorySlugs": [
      "kitchens"
    ]
  },
  {
    "slug": "lawn-mower-service-cost",
    "title": "Lawn Mower Service Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "treating-a-lawn",
    "title": "Lawn Treatment Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "laying-foundations",
    "title": "Laying Foundations Cost",
    "categorySlugs": [
      "conversions"
    ]
  },
  {
    "slug": "removing-lead-paint",
    "title": "Lead Paint Removal Cost",
    "categorySlugs": [
      "decorating-plastering",
      "external-finishes"
    ]
  },
  {
    "slug": "lean-to-conservatory",
    "title": "Lean-To Conservatory Cost",
    "categorySlugs": [
      "extensions"
    ]
  },
  {
    "slug": "installing-light-fittings",
    "title": "Light Fitting and Light Fixtures Cost",
    "categorySlugs": [
      "electrical-lighting"
    ]
  },
  {
    "slug": "lime-render",
    "title": "Lime Render Cost",
    "categorySlugs": [
      "external-finishes"
    ]
  },
  {
    "slug": "liquid-plastic-roofing",
    "title": "Liquid Plastic Roofing Cost: Prices & Guide",
    "categorySlugs": []
  },
  {
    "slug": "removing-a-load-bearing-wall",
    "title": "Load Bearing Wall Removal Cost",
    "categorySlugs": [
      "conversions"
    ]
  },
  {
    "slug": "get-your-locks-changed",
    "title": "Lock Change Cost",
    "categorySlugs": [
      "carpentry-windows-doors"
    ]
  },
  {
    "slug": "loft-boarding-cost",
    "title": "Loft Boarding Cost 2026",
    "categorySlugs": []
  },
  {
    "slug": "loft-conversion",
    "title": "Loft Conversion Cost",
    "categorySlugs": [
      "conversions"
    ]
  },
  {
    "slug": "loft-conversion-in-birmingham-cost",
    "title": "Loft Conversion Cost in Birmingham (2026 Prices)",
    "categorySlugs": []
  },
  {
    "slug": "loft-conversion-in-manchester-cost",
    "title": "Loft Conversion Cost in Manchester (2026 Prices)",
    "categorySlugs": []
  },
  {
    "slug": "loft-conversion-in-sheffield-cost",
    "title": "Loft Conversion Cost in Sheffield (2026 Prices)",
    "categorySlugs": []
  },
  {
    "slug": "loft-conversion-in-edinburgh-cost",
    "title": "Loft Conversion in Edinburgh Cost Guide (2026 Prices)",
    "categorySlugs": []
  },
  {
    "slug": "loft-conversion-in-glasgow-cost",
    "title": "Loft Conversion in Glasgow Cost Guide (2026 Prices)",
    "categorySlugs": []
  },
  {
    "slug": "loft-conversion-in-leeds-cost",
    "title": "Loft Conversion in Leeds Cost (2026 Prices)",
    "categorySlugs": []
  },
  {
    "slug": "loft-extension",
    "title": "Loft Extension Cost",
    "categorySlugs": [
      "extensions"
    ]
  },
  {
    "slug": "installing-a-loft-hatch",
    "title": "Loft Hatch Installation Cost Guide (2026 Update)",
    "categorySlugs": []
  },
  {
    "slug": "boarding-and-insulating-a-loft",
    "title": "Loft Insulation and Boarding Cost",
    "categorySlugs": [
      "energy-saving"
    ]
  },
  {
    "slug": "loft-insulation-cost",
    "title": "Loft Insulation Cost 2026",
    "categorySlugs": []
  },
  {
    "slug": "loft-ladder-installation-cost",
    "title": "Loft Ladder Installation Cost",
    "categorySlugs": [
      "carpentry-windows-doors"
    ]
  },
  {
    "slug": "installing-loft-legs",
    "title": "Loft Legs Installation Cost",
    "categorySlugs": [
      "carpentry-windows-doors"
    ]
  },
  {
    "slug": "installing-loft-lighting",
    "title": "Loft Light Installation Cost",
    "categorySlugs": [
      "electrical-lighting"
    ]
  },
  {
    "slug": "installing-a-log-burner",
    "title": "Log Burner Installation Cost",
    "categorySlugs": [
      "plumbing-heating"
    ]
  },
  {
    "slug": "liquefied-petroleum-gas-central-heating",
    "title": "LPG Central Heating Cost",
    "categorySlugs": [
      "plumbing-heating"
    ]
  },
  {
    "slug": "lvt-flooring",
    "title": "LVT Flooring Cost",
    "categorySlugs": [
      "flooring-carpets"
    ]
  },
  {
    "slug": "mansard-loft-conversion",
    "title": "Mansard Loft Conversion Cost",
    "categorySlugs": [
      "conversions"
    ]
  },
  {
    "slug": "metal-roof",
    "title": "Metal Roof Cost",
    "categorySlugs": [
      "roofs-chimneys"
    ]
  },
  {
    "slug": "microwave-repair",
    "title": "Microwave Repair Cost UK",
    "categorySlugs": []
  },
  {
    "slug": "monocouche-render",
    "title": "Monocouche Render Cost",
    "categorySlugs": [
      "external-finishes"
    ]
  },
  {
    "slug": "mould-removal",
    "title": "Mould Treatment 2026: How Much Does Mould Removal Cost?",
    "categorySlugs": []
  },
  {
    "slug": "moving-a-fireplace",
    "title": "Moving a Fireplace Cost",
    "categorySlugs": [
      "plumbing-heating"
    ]
  },
  {
    "slug": "multi-storey-extension",
    "title": "Multi Storey Extension Cost",
    "categorySlugs": [
      "extensions"
    ]
  },
  {
    "slug": "nest-installation",
    "title": "Nest Installation Cost",
    "categorySlugs": [
      "plumbing-heating"
    ]
  },
  {
    "slug": "full-bathroom-cost",
    "title": "New Bathroom Cost",
    "categorySlugs": [
      "bathrooms",
      "plumbing-heating"
    ]
  },
  {
    "slug": "new-driveway",
    "title": "New Driveway Cost",
    "categorySlugs": [
      "driveways-paving"
    ]
  },
  {
    "slug": "new-flooring",
    "title": "New Flooring Costs",
    "categorySlugs": [
      "flooring-carpets"
    ]
  },
  {
    "slug": "new-front-door",
    "title": "New Front Door Cost",
    "categorySlugs": [
      "carpentry-windows-doors"
    ]
  },
  {
    "slug": "garage-door-replacement",
    "title": "New Garage Door Cost",
    "categorySlugs": [
      "carpentry-windows-doors"
    ]
  },
  {
    "slug": "new-handrail",
    "title": "New Handrail Cost",
    "categorySlugs": [
      "carpentry-windows-doors"
    ]
  },
  {
    "slug": "new-plug-sockets",
    "title": "New Plug Socket Cost",
    "categorySlugs": [
      "electrical-lighting"
    ]
  },
  {
    "slug": "new-roof",
    "title": "New Roof Cost",
    "categorySlugs": [
      "roofs-chimneys"
    ]
  },
  {
    "slug": "installing-a-new-staircase",
    "title": "New Staircase Cost",
    "categorySlugs": [
      "carpentry-windows-doors"
    ]
  },
  {
    "slug": "replace-a-toilet",
    "title": "New Toilet Cost",
    "categorySlugs": [
      "bathrooms",
      "plumbing-heating"
    ]
  },
  {
    "slug": "new-window-opening",
    "title": "New Window Opening Cost",
    "categorySlugs": [
      "carpentry-windows-doors",
      "conversions"
    ]
  },
  {
    "slug": "new-window-costs",
    "title": "New Windows Cost",
    "categorySlugs": [
      "carpentry-windows-doors"
    ]
  },
  {
    "slug": "oak-porch-canopy",
    "title": "Oak Porch Canopy Cost",
    "categorySlugs": [
      "carpentry-windows-doors"
    ]
  },
  {
    "slug": "cost-of-installing-an-oil-boiler",
    "title": "Oil Boiler Installation Cost",
    "categorySlugs": [
      "plumbing-heating"
    ]
  },
  {
    "slug": "one-coat-plaster-cost",
    "title": "One Coat Plaster Cost",
    "categorySlugs": [
      "decorating-plastering"
    ]
  },
  {
    "slug": "open-up-fire-place",
    "title": "Open Up Fire Place Cost",
    "categorySlugs": [
      "plumbing-heating"
    ]
  },
  {
    "slug": "build-an-outbuilding",
    "title": "Outbuilding Cost",
    "categorySlugs": [
      "extensions"
    ]
  },
  {
    "slug": "installing-outdoor-lighting",
    "title": "Outdoor Lighting Installation Cost",
    "categorySlugs": [
      "electrical-lighting"
    ]
  },
  {
    "slug": "outside-socket",
    "title": "Outdoor Socket Installation Cost",
    "categorySlugs": [
      "electrical-lighting"
    ]
  },
  {
    "slug": "installing-an-outside-tap",
    "title": "Outside Tap Installation Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "oven-cleaning-cost",
    "title": "Oven Cleaning Cost Guide: How Much to Clean an Oven? (2026)",
    "categorySlugs": []
  },
  {
    "slug": "oven-repair",
    "title": "Oven Repair Cost in the UK",
    "categorySlugs": []
  },
  {
    "slug": "painting-a-garage-door",
    "title": "Painting a Garage Door Cost",
    "categorySlugs": [
      "decorating-plastering",
      "external-finishes"
    ]
  },
  {
    "slug": "palm-tree-removal",
    "title": "Palm Tree Removal Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "laying-parquet-flooring",
    "title": "Parquet Flooring Cost",
    "categorySlugs": [
      "flooring-carpets"
    ]
  },
  {
    "slug": "pat-testing-cost",
    "title": "PAT Testing Cost",
    "categorySlugs": [
      "electrical-lighting"
    ]
  },
  {
    "slug": "patio-door",
    "title": "Patio Door Installation Cost",
    "categorySlugs": [
      "carpentry-windows-doors"
    ]
  },
  {
    "slug": "penetrating-damp-treatment",
    "title": "Penetrating Damp Treatment Cost",
    "categorySlugs": [
      "conversions"
    ]
  },
  {
    "slug": "pergola-installation",
    "title": "Pergola Installation Costs",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "pest-control",
    "title": "Pest Control Prices List 2026: How Much Is Pest Control?",
    "categorySlugs": []
  },
  {
    "slug": "piggyback-loft-conversion",
    "title": "Piggyback Loft Conversion Cost Guide (2026)",
    "categorySlugs": []
  },
  {
    "slug": "pine-tree-removal",
    "title": "Pine Tree Removal Costs",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "pitched-dormer-loft-conversion",
    "title": "Pitched Dormer Loft Conversion Cost",
    "categorySlugs": [
      "roofs-chimneys"
    ]
  },
  {
    "slug": "plaster-coving",
    "title": "Plaster Coving Cost",
    "categorySlugs": [
      "decorating-plastering"
    ]
  },
  {
    "slug": "plastering-an-indoor-wall-cost",
    "title": "Plastering Costs",
    "categorySlugs": [
      "decorating-plastering"
    ]
  },
  {
    "slug": "polymer-render",
    "title": "Polymer Render Costs",
    "categorySlugs": [
      "external-finishes"
    ]
  },
  {
    "slug": "pond-removal",
    "title": "Pond Removal Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "pouring-concrete",
    "title": "Pouring Concrete Cost",
    "categorySlugs": [
      "driveways-paving"
    ]
  },
  {
    "slug": "power-flush-cost",
    "title": "Power Flush Cost",
    "categorySlugs": [
      "plumbing-heating"
    ]
  },
  {
    "slug": "installing-a-power-shower",
    "title": "Power Shower Installation Cost",
    "categorySlugs": [
      "bathrooms",
      "plumbing-heating"
    ]
  },
  {
    "slug": "pressure-washing",
    "title": "Pressure Washing Cost Guide (UK Prices 2026)",
    "categorySlugs": []
  },
  {
    "slug": "quartz-worktop",
    "title": "Quartz Worktop Cost Guide",
    "categorySlugs": []
  },
  {
    "slug": "remove-and-replace-a-radiator",
    "title": "Radiator Replacement Cost",
    "categorySlugs": [
      "plumbing-heating"
    ]
  },
  {
    "slug": "rat-exterminator",
    "title": "Rat Exterminator Cost: How Much Is Pest Control for Rats?",
    "categorySlugs": []
  },
  {
    "slug": "rear-dormer-loft-conversion",
    "title": "Rear Dormer Loft Conversion Cost Guide",
    "categorySlugs": []
  },
  {
    "slug": "rear-extension",
    "title": "Rear Extension Cost",
    "categorySlugs": [
      "extensions"
    ]
  },
  {
    "slug": "remove-a-tree-stump",
    "title": "Remove a Tree Stump Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "removing-partition-walls",
    "title": "Removing a Partition Wall Cost",
    "categorySlugs": [
      "carpentry-windows-doors"
    ]
  },
  {
    "slug": "render-cleaning",
    "title": "Render Cleaning Cost (UK Guide 2026)",
    "categorySlugs": [
      "decorating-plastering"
    ]
  },
  {
    "slug": "staircase-renovation",
    "title": "Renovating a Staircase Cost",
    "categorySlugs": [
      "carpentry-windows-doors",
      "decorating-plastering",
      "external-finishes"
    ]
  },
  {
    "slug": "repairing-roof-joist-costs",
    "title": "Repairing Roof Joist Cost",
    "categorySlugs": [
      "carpentry-windows-doors",
      "roofs-chimneys"
    ]
  },
  {
    "slug": "replace-bath-with-walk-in-shower",
    "title": "Replace Bath with Walk-in Shower Cost",
    "categorySlugs": [
      "bathrooms"
    ]
  },
  {
    "slug": "replace-eaves-felt",
    "title": "Replace Eaves Felt Cost",
    "categorySlugs": [
      "roofs-chimneys"
    ]
  },
  {
    "slug": "replace-roof-valley",
    "title": "Replace Roof Valley Cost",
    "categorySlugs": [
      "roofs-chimneys"
    ]
  },
  {
    "slug": "repointing-patio",
    "title": "Repointing a Patio Costs Guide 2026: How Much to Repoint a Patio?",
    "categorySlugs": []
  },
  {
    "slug": "installing-a-resin-driveway-cost",
    "title": "Resin Driveway Cost",
    "categorySlugs": [
      "driveways-paving"
    ]
  },
  {
    "slug": "resin-driveway-repair",
    "title": "Resin Driveway Repair Cost",
    "categorySlugs": [
      "driveways-paving"
    ]
  },
  {
    "slug": "retaining-wall",
    "title": "Retaining Wall Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "replacing-roof-ridge-tiles",
    "title": "Ridge Tile Replacement Cost",
    "categorySlugs": [
      "roofs-chimneys"
    ]
  },
  {
    "slug": "treating-rising-damp",
    "title": "Rising Damp Treatment Cost",
    "categorySlugs": [
      "plumbing-heating",
      "external-finishes"
    ]
  },
  {
    "slug": "rockery-installation",
    "title": "Rockery Installation Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "pressure-washing-your-roof",
    "title": "Roof Cleaning Cost",
    "categorySlugs": [
      "roofs-chimneys"
    ]
  },
  {
    "slug": "roof-inspection",
    "title": "Roof Inspection Cost Guide (2026)",
    "categorySlugs": []
  },
  {
    "slug": "roof-insulation",
    "title": "Roof Insulation Cost: How Much Is Loft Insulation? [2026]",
    "categorySlugs": []
  },
  {
    "slug": "roof-lantern",
    "title": "Roof Lantern Cost",
    "categorySlugs": [
      "carpentry-windows-doors",
      "roofs-chimneys"
    ]
  },
  {
    "slug": "roof-leak-repair",
    "title": "Roof Leak Repair Cost Guide (UK Prices 2026)",
    "categorySlugs": []
  },
  {
    "slug": "roof-lift-loft-conversion",
    "title": "Roof Lift Loft Conversion Cost",
    "categorySlugs": [
      "conversions",
      "roofs-chimneys"
    ]
  },
  {
    "slug": "roof-painting",
    "title": "Roof Painting Cost: How Much Does It Cost to Paint a Roof?",
    "categorySlugs": []
  },
  {
    "slug": "roof-maintenance",
    "title": "Roof Repair Cost",
    "categorySlugs": [
      "roofs-chimneys"
    ]
  },
  {
    "slug": "roof-survey",
    "title": "Roof Survey Cost",
    "categorySlugs": [
      "roofs-chimneys"
    ]
  },
  {
    "slug": "roof-truss",
    "title": "Roof Truss Cost",
    "categorySlugs": [
      "roofs-chimneys"
    ]
  },
  {
    "slug": "loft-vent-installation",
    "title": "Roof Vents Cost Guide 2026: How Much to Install a Roof Vent?",
    "categorySlugs": []
  },
  {
    "slug": "installing-rsj",
    "title": "RSJ Installation Cost",
    "categorySlugs": [
      "extensions"
    ]
  },
  {
    "slug": "rubber-roofing",
    "title": "Rubber Roofing Cost",
    "categorySlugs": [
      "roofs-chimneys"
    ]
  },
  {
    "slug": "satellite-dish-installation",
    "title": "Satellite Dish Installation Cost",
    "categorySlugs": [
      "electrical-lighting"
    ]
  },
  {
    "slug": "secondary-glazing-cost",
    "title": "Secondary Glazing Cost",
    "categorySlugs": [
      "carpentry-windows-doors",
      "energy-saving"
    ]
  },
  {
    "slug": "security-lights-installation",
    "title": "Security Light Installation Cost",
    "categorySlugs": [
      "electrical-lighting"
    ]
  },
  {
    "slug": "cleaning-and-emptying-septic-tank",
    "title": "Septic Tank Emptying Cost",
    "categorySlugs": [
      "drainage"
    ]
  },
  {
    "slug": "installing-septic-tank",
    "title": "Septic Tank Installation Cost",
    "categorySlugs": [
      "drainage"
    ]
  },
  {
    "slug": "building-a-garden-shed",
    "title": "Shed Installation Cost Guide",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "removing-a-shed",
    "title": "Shed Removal Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "shed-roof-replacement",
    "title": "Shed Roof Replacement Cost",
    "categorySlugs": [
      "roofs-chimneys"
    ]
  },
  {
    "slug": "side-dormer-loft-conversion",
    "title": "Side Dormer Loft Conversion Cost Guide 2026",
    "categorySlugs": []
  },
  {
    "slug": "side-extension",
    "title": "Side Return Extension Cost",
    "categorySlugs": [
      "extensions"
    ]
  },
  {
    "slug": "silicone-render",
    "title": "Silicone Render Cost",
    "categorySlugs": [
      "external-finishes"
    ]
  },
  {
    "slug": "single-story-extension",
    "title": "Single Storey Extension Cost",
    "categorySlugs": [
      "extensions"
    ]
  },
  {
    "slug": "skip-hire",
    "title": "Skip Hire Cost",
    "categorySlugs": [
      "conversions",
      "decorating-plastering",
      "extensions"
    ]
  },
  {
    "slug": "skirting-board-heating",
    "title": "Skirting Board Heating Cost",
    "categorySlugs": [
      "plumbing-heating"
    ]
  },
  {
    "slug": "painting-skirting-boards",
    "title": "Skirting Board Painting Cost",
    "categorySlugs": [
      "decorating-plastering",
      "external-finishes"
    ]
  },
  {
    "slug": "slate-roof",
    "title": "Slate Roof Cost",
    "categorySlugs": [
      "roofs-chimneys"
    ]
  },
  {
    "slug": "smart-lighting",
    "title": "Smart Lighting Cost",
    "categorySlugs": [
      "electrical-lighting"
    ]
  },
  {
    "slug": "smart-meter-installation",
    "title": "Smart Meter Installation Cost",
    "categorySlugs": [
      "electrical-lighting"
    ]
  },
  {
    "slug": "smart-thermostat-cost",
    "title": "Smart Thermostat Installation Cost",
    "categorySlugs": [
      "plumbing-heating"
    ]
  },
  {
    "slug": "install-a-fire-alarm",
    "title": "Smoke Alarm Installation Cost",
    "categorySlugs": [
      "electrical-lighting"
    ]
  },
  {
    "slug": "install-soak-away-drain",
    "title": "Soakaway Installation Cost",
    "categorySlugs": [
      "drainage"
    ]
  },
  {
    "slug": "soffit-lighting-installation",
    "title": "Soffit Lighting Installation Cost",
    "categorySlugs": [
      "electrical-lighting"
    ]
  },
  {
    "slug": "solar-battery-storage-system",
    "title": "Solar Battery Storage Cost Guide (UK Prices 2026)",
    "categorySlugs": []
  },
  {
    "slug": "solar-panel-cleaning-cost",
    "title": "Solar Panel Cleaning Cost",
    "categorySlugs": [
      "energy-saving"
    ]
  },
  {
    "slug": "solar-panel-installation-costs",
    "title": "Solar Panel Installation Cost",
    "categorySlugs": [
      "energy-saving"
    ]
  },
  {
    "slug": "solar-panel-maintenance",
    "title": "Solar Panel Maintenance Cost UK 2026",
    "categorySlugs": []
  },
  {
    "slug": "solar-roof-tiles-cost",
    "title": "Solar Roof Tiles Cost",
    "categorySlugs": [
      "energy-saving",
      "roofs-chimneys"
    ]
  },
  {
    "slug": "spray-foam-removal",
    "title": "Spray Foam Removal Cost Guide (2026 Update)",
    "categorySlugs": []
  },
  {
    "slug": "staining-a-fence",
    "title": "Staining a Fence Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "staining-your-sheds-and-fences",
    "title": "Staining Sheds and Fences Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "staircase-painting",
    "title": "Staircase Painting Cost",
    "categorySlugs": [
      "decorating-plastering",
      "external-finishes"
    ]
  },
  {
    "slug": "steam-shower-installation-cost",
    "title": "Steam Shower Cost",
    "categorySlugs": [
      "bathrooms",
      "plumbing-heating"
    ]
  },
  {
    "slug": "structural-engineer",
    "title": "Structural Engineer Costs",
    "categorySlugs": [
      "conversions"
    ]
  },
  {
    "slug": "fix-subsidence-cost",
    "title": "Subsidence Repair Cost Guide (2026 Update)",
    "categorySlugs": []
  },
  {
    "slug": "building-a-summer-house",
    "title": "Summer House Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "installing-a-sun-tunnel",
    "title": "Sun Tunnel Installation Cost",
    "categorySlugs": [
      "roofs-chimneys"
    ]
  },
  {
    "slug": "installing-a-garden-swimming-pool",
    "title": "Swimming Pool Installation Cost",
    "categorySlugs": [
      "conversions",
      "gardens-fences"
    ]
  },
  {
    "slug": "tankless-water-heater-installation",
    "title": "Tankless Water Heater Installation Cost",
    "categorySlugs": [
      "plumbing-heating"
    ]
  },
  {
    "slug": "replacing-bath-sink-taps",
    "title": "Tap Replacement Cost",
    "categorySlugs": [
      "bathrooms"
    ]
  },
  {
    "slug": "tarmacing-driveway",
    "title": "Tarmac Driveway Cost",
    "categorySlugs": [
      "driveways-paving"
    ]
  },
  {
    "slug": "tarmac-driveway-repair",
    "title": "Tarmac Driveway Repair Cost",
    "categorySlugs": [
      "driveways-paving"
    ]
  },
  {
    "slug": "thatched-roof-installation",
    "title": "Thatched Roof Cost",
    "categorySlugs": [
      "roofs-chimneys"
    ]
  },
  {
    "slug": "installing-a-thermal-store",
    "title": "Thermal Energy Store Cost",
    "categorySlugs": [
      "plumbing-heating"
    ]
  },
  {
    "slug": "timber-cladding",
    "title": "Timber Cladding Cost",
    "categorySlugs": [
      "carpentry-windows-doors"
    ]
  },
  {
    "slug": "timber-decking",
    "title": "Timber Decking Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "timber-frame-extension",
    "title": "Timber Frame Extension Cost",
    "categorySlugs": [
      "extensions"
    ]
  },
  {
    "slug": "tree-crown-reduction",
    "title": "Tree Crown Reduction Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "tree-felling",
    "title": "Tree Removal Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "tree-root-removal",
    "title": "Tree Root Removal Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "having-a-tree-trimmed-or-pruned",
    "title": "Tree Trimming Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  },
  {
    "slug": "triple-glazed-windows",
    "title": "Triple Glazed Windows Cost",
    "categorySlugs": [
      "carpentry-windows-doors",
      "energy-saving"
    ]
  },
  {
    "slug": "tumble-dryer-repair",
    "title": "Tumble Dryer Repair Cost UK",
    "categorySlugs": []
  },
  {
    "slug": "aerial-cable-installation",
    "title": "TV Aerial Installation Cost",
    "categorySlugs": [
      "electrical-lighting",
      "roofs-chimneys"
    ]
  },
  {
    "slug": "hanging-a-tv",
    "title": "TV Wall Mount Installation Cost Guide (2026 Update)",
    "categorySlugs": []
  },
  {
    "slug": "underfloor-heating",
    "title": "Underfloor Heating Cost",
    "categorySlugs": [
      "flooring-carpets",
      "plumbing-heating"
    ]
  },
  {
    "slug": "underpinning-a-house",
    "title": "Underpinning Cost",
    "categorySlugs": [
      "extensions"
    ]
  },
  {
    "slug": "installing-upvc-cladding",
    "title": "uPVC House Cladding Cost",
    "categorySlugs": [
      "carpentry-windows-doors",
      "roofs-chimneys"
    ]
  },
  {
    "slug": "upvc-spray-painting",
    "title": "uPVC Spraying Cost",
    "categorySlugs": [
      "decorating-plastering"
    ]
  },
  {
    "slug": "velux-loft-conversion",
    "title": "Velux Loft Conversion Cost",
    "categorySlugs": [
      "roofs-chimneys"
    ]
  },
  {
    "slug": "venetian-plaster",
    "title": "Venetian Plaster Price",
    "categorySlugs": [
      "decorating-plastering"
    ]
  },
  {
    "slug": "vertical-radiator-installation",
    "title": "Vertical Radiator Installation Cost",
    "categorySlugs": [
      "plumbing-heating"
    ]
  },
  {
    "slug": "vinyl-flooring-costs",
    "title": "Vinyl Flooring Cost",
    "categorySlugs": [
      "flooring-carpets"
    ]
  },
  {
    "slug": "walk-in-bath-cost",
    "title": "Walk in Bath Cost",
    "categorySlugs": [
      "bathrooms"
    ]
  },
  {
    "slug": "installing-wall-panelling",
    "title": "Wall Panelling Cost",
    "categorySlugs": [
      "carpentry-windows-doors"
    ]
  },
  {
    "slug": "removing-hanging-wallpaper-cost",
    "title": "Wallpaper Removal Cost",
    "categorySlugs": [
      "decorating-plastering"
    ]
  },
  {
    "slug": "washing-machine-repair",
    "title": "Washing Machine Repair Costs in the UK",
    "categorySlugs": []
  },
  {
    "slug": "water-softener-installation",
    "title": "Water Softener Installation Cost",
    "categorySlugs": [
      "bathrooms",
      "plumbing-heating"
    ]
  },
  {
    "slug": "water-supply-pipe-replacement",
    "title": "Water Supply Pipe Replacement Cost",
    "categorySlugs": [
      "plumbing-heating"
    ]
  },
  {
    "slug": "wet-room-cost",
    "title": "Wet Room Installation Cost",
    "categorySlugs": [
      "bathrooms"
    ]
  },
  {
    "slug": "wooden-bin-cover",
    "title": "Wheelie Bin Store Cost",
    "categorySlugs": [
      "carpentry-windows-doors",
      "gardens-fences"
    ]
  },
  {
    "slug": "windows-clean-com-res",
    "title": "Window Cleaning Cost",
    "categorySlugs": [
      "carpentry-windows-doors"
    ]
  },
  {
    "slug": "blown-windows",
    "title": "Window Glass Replacement Cost",
    "categorySlugs": [
      "carpentry-windows-doors"
    ]
  },
  {
    "slug": "window-sill-replacement",
    "title": "Window Sill Replacement Cost",
    "categorySlugs": [
      "carpentry-windows-doors"
    ]
  },
  {
    "slug": "restoring-wooden-flooring",
    "title": "Wooden Floor Restoration Cost",
    "categorySlugs": [
      "flooring-carpets"
    ]
  },
  {
    "slug": "installing-wood-floor",
    "title": "Wooden Flooring Installation Cost",
    "categorySlugs": [
      "flooring-carpets"
    ]
  },
  {
    "slug": "woodworm-treatment-costs",
    "title": "Woodworm Treatment Cost",
    "categorySlugs": [
      "carpentry-windows-doors"
    ]
  },
  {
    "slug": "wrought-iron-fencing",
    "title": "Wrought Iron Fencing Cost",
    "categorySlugs": [
      "gardens-fences"
    ]
  }
];

export const COST_JOB_BY_SLUG = new Map(COST_JOB_LISTINGS.map((job) => [job.slug, job]));
